version: '3.7'

services:

##### Node API Container
  api:
    build: ./api
    expose:
      - ${API_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${API_SERVER_PORT}
    ports:
      - ${API_SERVER_PORT}:${API_SERVER_PORT}
    volumes:
      - ./api/src/:/srv/api/src
    command: npm run dev

##### React Frontend Container

  dashboard:
    build: ./dashboard
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./dashboard/src:/srv/dashboard/src
      - ./dashboard/public:/srv/dashboard/public
    links:
      - api
    command: npm run start